name: encrypt-secret-artifact

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  create-and-encrypt-artifact:
    if: github.repository == 'jeremyary/test-action'
    runs-on: ubuntu-latest
    env:
      GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
      ANOTHER_SECRET: ${{ secrets.ANOTHER_SECRET }}
    steps:
      - name: secret to file
        id: secret-to-file
        run: |
          echo -e "GPG_PUBLIC_KEY:\n$GPG_PUBLIC_KEY \n\n" > ./file.txt
          echo -e "GPG_PUBLIC_KEY:\n$GPG_PRIVATE_KEY \n\n" >> ./file.txt
          echo -e "SUPER_SECRET:\n$SUPER_SECRET \n\n" >> ./file.txt
          echo -e "ANOTHER_SECRET:\n$ANOTHER_SECRET \n\n" >> ./file.txt
      - name: encrypt file
        id: encrypt-file
        run: |
          echo -n "$GPG_PUBLIC_KEY" > ./public-key
          echo -n "$GPG_PRIVATE_KEY" > ./private-key
          gpg --import --batch ./public-key
          gpg --import --batch ./private-key
#      - name: show keys
#        id: show-keys
#        run: |
#          echo "show keys"
#          gpg --list-secret-keys --keyid-format=long
      - name: gpg output
        id: gpg-output
        run: |
          gpg --batch --trust-model always --output artifact.gpg --encrypt --recipient jary@redhat.com ./file.txt
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: upload-artifact
          path: artifact.gpg
          retention-days: 1
